Configuration:
  Mobs:
    EnableAIModifiers: true
    EnableTimerSkills: true
    EnableThreatTables: true
    EnablePlayerFactions: true
    EnableLegacySkills: true
    KillMessagePrefix: ""
    ShowHealth:
      Radius: 25
      Format: <mob.name> - <mob.php> (<mob.hp> / <mob.mhp>)
    Scaling:
      Default:
        Enabled: true
        PerBlocksFromSpawn: 250
      world2:
        Enabled: true
        PerBlocksFromSpawn: 250
      world2_nether:
        Enabled: false
        PerBlocksFromSpawn: 100
    DefaultLevelModifiers:
      Health: 0.1
      Armor: 0
      Damage: 0
      KnockbackResistance: 0
      Power: 0
  MobDrops:
    DefaultDropMethod: VANILLA
    DoLootsplosionByDefault: false
    DoHologramNameByDefault: false
    DoItemGlowByDefault: false
    DoItemBeamByDefault: false
    DoItemVFXByDefault: false
    DefaultItemVFX:
      Material: POTION
      Model: 1
    DoPerPlayerDropsByDefault: false
    DoClientsideDropsByDefault: false
    MinimumDamagePercentForDrops: 1%
    DefaultDeathHologram: []
    DefaultLeaderboardTimeout: 6000
    DefaultDeathChatMessage: []
  MobEggs:
    Material: PIG_SPAWN_EGG
    DefaultDisplay: <mob.name> Spawn Egg
    DefaultLore:
      - <dark_gray>A Mythical Egg that can</dark_gray>
      - <dark_gray>be used to resurrect a</dark_gray>
      - <dark_gray><mob.name></dark_gray>
